# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: paxos.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='paxos.proto',
  package='paxos',
  syntax='proto3',
  serialized_pb=_b('\n\x0bpaxos.proto\x12\x05paxos\"\'\n\tDataReply\x12\x0c\n\x04view\x18\x01 \x01(\x05\x12\x0c\n\x04hash\x18\x02 \x01(\x05\"\x16\n\x07HBReply\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\x05\"\x19\n\nLearnReply\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\x05\">\n\tLearnSend\x12\t\n\x01n\x18\x01 \x01(\x05\x12\x0b\n\x03val\x18\x02 \x01(\t\x12\x0b\n\x03rid\x18\x03 \x01(\x05\x12\x0c\n\x04slot\x18\x04 \x01(\x05\"2\n\nAcceptSend\x12\t\n\x01n\x18\x01 \x01(\x05\x12\x0b\n\x03val\x18\x02 \x01(\t\x12\x0c\n\x04slot\x18\x03 \x01(\x05\"\x1b\n\x0b\x41\x63\x63\x65ptReply\x12\x0c\n\x04view\x18\x01 \x01(\x05\"\x1f\n\x0bPrepareSend\x12\x10\n\x08proposal\x18\x01 \x01(\x05\"r\n\x0cPromiseReply\x12\x19\n\x11highest_proposals\x18\x01 \x03(\x05\x12\x16\n\x0ehighest_values\x18\x02 \x03(\t\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x03 \x03(\x05\x12\x0f\n\x07ignored\x18\x04 \x01(\x05\x12\x0c\n\x04view\x18\x05 \x01(\x05\"9\n\x0b\x43hatRequest\x12\x0c\n\x04mesg\x18\x01 \x01(\t\x12\x0f\n\x07seq_num\x18\x02 \x01(\x05\x12\x0b\n\x03rid\x18\x03 \x01(\x05\"*\n\tChatReply\x12\x0c\n\x04mesg\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x05\"\x07\n\x05\x45mpty2q\n\x07\x43hatter\x12\x39\n\x0fSendChatMessage\x12\x12.paxos.ChatRequest\x1a\x10.paxos.ChatReply\"\x00\x12+\n\x07GetData\x12\x0c.paxos.Empty\x1a\x10.paxos.DataReply\"\x00\x32\xcd\x01\n\x05Paxos\x12\x34\n\x07Prepare\x12\x12.paxos.PrepareSend\x1a\x13.paxos.PromiseReply\"\x00\x12\x31\n\x06\x41\x63\x63\x65pt\x12\x11.paxos.AcceptSend\x1a\x12.paxos.AcceptReply\"\x00\x12.\n\x05Learn\x12\x10.paxos.LearnSend\x1a\x11.paxos.LearnReply\"\x00\x12+\n\tHeartBeat\x12\x0c.paxos.Empty\x1a\x0e.paxos.HBReply\"\x00\x42\x06\xa2\x02\x03RTGb\x06proto3')
)




_DATAREPLY = _descriptor.Descriptor(
  name='DataReply',
  full_name='paxos.DataReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='view', full_name='paxos.DataReply.view', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hash', full_name='paxos.DataReply.hash', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=61,
)


_HBREPLY = _descriptor.Descriptor(
  name='HBReply',
  full_name='paxos.HBReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ack', full_name='paxos.HBReply.ack', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=85,
)


_LEARNREPLY = _descriptor.Descriptor(
  name='LearnReply',
  full_name='paxos.LearnReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ack', full_name='paxos.LearnReply.ack', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=112,
)


_LEARNSEND = _descriptor.Descriptor(
  name='LearnSend',
  full_name='paxos.LearnSend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='n', full_name='paxos.LearnSend.n', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='val', full_name='paxos.LearnSend.val', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rid', full_name='paxos.LearnSend.rid', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='slot', full_name='paxos.LearnSend.slot', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=176,
)


_ACCEPTSEND = _descriptor.Descriptor(
  name='AcceptSend',
  full_name='paxos.AcceptSend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='n', full_name='paxos.AcceptSend.n', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='val', full_name='paxos.AcceptSend.val', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='slot', full_name='paxos.AcceptSend.slot', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=228,
)


_ACCEPTREPLY = _descriptor.Descriptor(
  name='AcceptReply',
  full_name='paxos.AcceptReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='view', full_name='paxos.AcceptReply.view', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=257,
)


_PREPARESEND = _descriptor.Descriptor(
  name='PrepareSend',
  full_name='paxos.PrepareSend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proposal', full_name='paxos.PrepareSend.proposal', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=290,
)


_PROMISEREPLY = _descriptor.Descriptor(
  name='PromiseReply',
  full_name='paxos.PromiseReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='highest_proposals', full_name='paxos.PromiseReply.highest_proposals', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='highest_values', full_name='paxos.PromiseReply.highest_values', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='accepted', full_name='paxos.PromiseReply.accepted', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ignored', full_name='paxos.PromiseReply.ignored', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='view', full_name='paxos.PromiseReply.view', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=292,
  serialized_end=406,
)


_CHATREQUEST = _descriptor.Descriptor(
  name='ChatRequest',
  full_name='paxos.ChatRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mesg', full_name='paxos.ChatRequest.mesg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seq_num', full_name='paxos.ChatRequest.seq_num', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rid', full_name='paxos.ChatRequest.rid', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=408,
  serialized_end=465,
)


_CHATREPLY = _descriptor.Descriptor(
  name='ChatReply',
  full_name='paxos.ChatReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mesg', full_name='paxos.ChatReply.mesg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='success', full_name='paxos.ChatReply.success', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=467,
  serialized_end=509,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='paxos.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=511,
  serialized_end=518,
)

DESCRIPTOR.message_types_by_name['DataReply'] = _DATAREPLY
DESCRIPTOR.message_types_by_name['HBReply'] = _HBREPLY
DESCRIPTOR.message_types_by_name['LearnReply'] = _LEARNREPLY
DESCRIPTOR.message_types_by_name['LearnSend'] = _LEARNSEND
DESCRIPTOR.message_types_by_name['AcceptSend'] = _ACCEPTSEND
DESCRIPTOR.message_types_by_name['AcceptReply'] = _ACCEPTREPLY
DESCRIPTOR.message_types_by_name['PrepareSend'] = _PREPARESEND
DESCRIPTOR.message_types_by_name['PromiseReply'] = _PROMISEREPLY
DESCRIPTOR.message_types_by_name['ChatRequest'] = _CHATREQUEST
DESCRIPTOR.message_types_by_name['ChatReply'] = _CHATREPLY
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataReply = _reflection.GeneratedProtocolMessageType('DataReply', (_message.Message,), dict(
  DESCRIPTOR = _DATAREPLY,
  __module__ = 'paxos_pb2'
  # @@protoc_insertion_point(class_scope:paxos.DataReply)
  ))
_sym_db.RegisterMessage(DataReply)

HBReply = _reflection.GeneratedProtocolMessageType('HBReply', (_message.Message,), dict(
  DESCRIPTOR = _HBREPLY,
  __module__ = 'paxos_pb2'
  # @@protoc_insertion_point(class_scope:paxos.HBReply)
  ))
_sym_db.RegisterMessage(HBReply)

LearnReply = _reflection.GeneratedProtocolMessageType('LearnReply', (_message.Message,), dict(
  DESCRIPTOR = _LEARNREPLY,
  __module__ = 'paxos_pb2'
  # @@protoc_insertion_point(class_scope:paxos.LearnReply)
  ))
_sym_db.RegisterMessage(LearnReply)

LearnSend = _reflection.GeneratedProtocolMessageType('LearnSend', (_message.Message,), dict(
  DESCRIPTOR = _LEARNSEND,
  __module__ = 'paxos_pb2'
  # @@protoc_insertion_point(class_scope:paxos.LearnSend)
  ))
_sym_db.RegisterMessage(LearnSend)

AcceptSend = _reflection.GeneratedProtocolMessageType('AcceptSend', (_message.Message,), dict(
  DESCRIPTOR = _ACCEPTSEND,
  __module__ = 'paxos_pb2'
  # @@protoc_insertion_point(class_scope:paxos.AcceptSend)
  ))
_sym_db.RegisterMessage(AcceptSend)

AcceptReply = _reflection.GeneratedProtocolMessageType('AcceptReply', (_message.Message,), dict(
  DESCRIPTOR = _ACCEPTREPLY,
  __module__ = 'paxos_pb2'
  # @@protoc_insertion_point(class_scope:paxos.AcceptReply)
  ))
_sym_db.RegisterMessage(AcceptReply)

PrepareSend = _reflection.GeneratedProtocolMessageType('PrepareSend', (_message.Message,), dict(
  DESCRIPTOR = _PREPARESEND,
  __module__ = 'paxos_pb2'
  # @@protoc_insertion_point(class_scope:paxos.PrepareSend)
  ))
_sym_db.RegisterMessage(PrepareSend)

PromiseReply = _reflection.GeneratedProtocolMessageType('PromiseReply', (_message.Message,), dict(
  DESCRIPTOR = _PROMISEREPLY,
  __module__ = 'paxos_pb2'
  # @@protoc_insertion_point(class_scope:paxos.PromiseReply)
  ))
_sym_db.RegisterMessage(PromiseReply)

ChatRequest = _reflection.GeneratedProtocolMessageType('ChatRequest', (_message.Message,), dict(
  DESCRIPTOR = _CHATREQUEST,
  __module__ = 'paxos_pb2'
  # @@protoc_insertion_point(class_scope:paxos.ChatRequest)
  ))
_sym_db.RegisterMessage(ChatRequest)

ChatReply = _reflection.GeneratedProtocolMessageType('ChatReply', (_message.Message,), dict(
  DESCRIPTOR = _CHATREPLY,
  __module__ = 'paxos_pb2'
  # @@protoc_insertion_point(class_scope:paxos.ChatReply)
  ))
_sym_db.RegisterMessage(ChatReply)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'paxos_pb2'
  # @@protoc_insertion_point(class_scope:paxos.Empty)
  ))
_sym_db.RegisterMessage(Empty)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\242\002\003RTG'))

_CHATTER = _descriptor.ServiceDescriptor(
  name='Chatter',
  full_name='paxos.Chatter',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=520,
  serialized_end=633,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendChatMessage',
    full_name='paxos.Chatter.SendChatMessage',
    index=0,
    containing_service=None,
    input_type=_CHATREQUEST,
    output_type=_CHATREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetData',
    full_name='paxos.Chatter.GetData',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_DATAREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHATTER)

DESCRIPTOR.services_by_name['Chatter'] = _CHATTER


_PAXOS = _descriptor.ServiceDescriptor(
  name='Paxos',
  full_name='paxos.Paxos',
  file=DESCRIPTOR,
  index=1,
  options=None,
  serialized_start=636,
  serialized_end=841,
  methods=[
  _descriptor.MethodDescriptor(
    name='Prepare',
    full_name='paxos.Paxos.Prepare',
    index=0,
    containing_service=None,
    input_type=_PREPARESEND,
    output_type=_PROMISEREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Accept',
    full_name='paxos.Paxos.Accept',
    index=1,
    containing_service=None,
    input_type=_ACCEPTSEND,
    output_type=_ACCEPTREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Learn',
    full_name='paxos.Paxos.Learn',
    index=2,
    containing_service=None,
    input_type=_LEARNSEND,
    output_type=_LEARNREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='HeartBeat',
    full_name='paxos.Paxos.HeartBeat',
    index=3,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_HBREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PAXOS)

DESCRIPTOR.services_by_name['Paxos'] = _PAXOS

# @@protoc_insertion_point(module_scope)
